### PR TITLE
Add Arabic Localization

### PR DESCRIPTION
**Pull request by AmrIKhudair**
This PR/Translation is about #28 .

**files translated**:
  - [x] `def/ar/about.cson`
  - [x] `def/ar/context.cson`
  - [x] `def/ar/menu_darwin.cson`
  - [x] `def/ar/menu_linux.cson`
  - [x] `def/ar/menu_win32.cson`
  - [x] `def/ar/settings.cson`
  - [x] `def/ar/welcome.cson`

**validation**
  - [x] I've validated my translation locally by running

`npm run validation -- --locale ar`

### CODE REVIEW

**Comment by AmrIKhudair** [comment]
Will you not pull?

**Comment by liuderchi** [comment]
Sorry for the late review

**Comment by liuderchi** [comment]
TODO for myself:
  - [ ] add author to CODEOWNER, README
  - [ ] update i81n progress in README

**Comment by AmrIKhudair** [comment]
It's ok bro. I am always ready to maintain the local in case of translation typos or new strings to be translated.

**Comment by AmrIKhudair** [comment]
BTW Arabic locales should show in right-to-left layout, do you think there might be a way to achieve this?

**Comment by liuderchi** [comment]
How does right-to-left layout possibly look like?

For example, menu item starts from right to left?
  like `Help, Window ... View, Edit, File`

**Comment by LorenzoAncora** [comment]
> For example, menu item starts from right to left?
like Help, Window ... View, Edit, File

@liuderchi I asked myself the same question several times. I discovered that Microsoft<sup>&reg;</sup> Developer Network has the [correct answer](https://docs.microsoft.com/it-it/globalization/localizability/mirroring-awareness): yes.
If you don't trust them, compare Google<sup>&reg;</sup> in [Arabic](https://news.google.com/news/?hl=ar&ned=ar_me&gl=ME) VS Google in [English](https://news.google.com/news/?ned=us&gl=US&hl=en), it is all mirrored... ;-)

**Comment by AmrIKhudair** [comment]
Generally it should be flipped vertically so for example:
The first menu to the far right, follows it to the left the second, and the third, etc
That is achieved automatically in Linux systems (no idea about other systems), so clearly that is not what I mean.

I mean that everything in the UI should be flipped, e.g. tabs start from right, the tree view is to the right, its branches grow to the left, etc

**Comment by LorenzoAncora** [comment]
> [...]
I mean that everything in the UI should be flipped, e.g. tabs start from right, the tree view is to the right, its branches grow to the left, etc

@AmrIKhudair as I said before, yes. The official page I've posted [shows](https://docs.microsoft.com/en-us/media/hubs/globalization/IC124125.jpg) that there is a tree view to the right, with branches that grow from right to left.  When people reads from right to left, controls should be like in a mirror.

A small note: for the menus, I do not think it is enough to simply mirror the bar, you must also make sure that the menus are comfortable to use compared to the default WM of the target systems. It's no coincidence that the menus are special widgets in most graphic toolkits (at least the ones I've tried so far). The OS provides you with all the means to manage the mirroring of the GUI, but end-user feedback is the best answer.

**Pull request merged**
