### PR TITLE
Update Czech translation

### PR DESCRIPTION
**Pull request by pervoj**
This PR/Translation is about #188.

**files updated**:

  - [x] `def/--LOCALE-CODE--/about.cson`
  - [x] `def/--LOCALE-CODE--/context.cson`
  - [x] `def/--LOCALE-CODE--/menu_darwin.cson`
  - [x] `def/--LOCALE-CODE--/menu_linux.cson`
  - [ ] `def/--LOCALE-CODE--/menu_win32.cson`
  - [x] `def/--LOCALE-CODE--/settings.cson`
  - [x] `def/--LOCALE-CODE--/welcome.cson`

**files translated**:

  - [ ] `def/--LOCALE-CODE--/about.cson`
  - [ ] `def/--LOCALE-CODE--/context.cson`
  - [ ] `def/--LOCALE-CODE--/menu_darwin.cson`
  - [x] `def/--LOCALE-CODE--/menu_linux.cson`
  - [ ] `def/--LOCALE-CODE--/menu_win32.cson`
  - [ ] `def/--LOCALE-CODE--/settings.cson`
  - [ ] `def/--LOCALE-CODE--/welcome.cson`

**validation**
  - [ ] I've validated my translation locally by running

`npm run validation -- --locale MY_LOCALE`

### CODE REVIEW

**Comment by pervoj** [comment]
Note: `cz` is code for country (Czech Republic) and `cs` is code for language (Czech). Can you change it please?

**Comment by liuderchi** [comment]
@pervoj Sorry for late review!
Thanks for the feedback and I will rename `cz` as `cs in next release!

**Review by liuderchi — APPROVED** [review]
Thanks for your contribution! 💯

**Comment by liuderchi** [comment]
@pervoj we now could use `cs` language code in latest release `v0.25.2`
https://atom.io/packages/atom-i18n

Screen Shot 2021-04-17 at 12 55 42

**Comment by pervoj** [comment]
@liuderchi Now there are two Czech languages in the settings. In the `package.json` is first with `cs` and second with `cz`. Is it an intention or a mistake?

**Comment by liuderchi** [comment]
@pervoj Thanks! It was an intention to test whether Atom would backward support both `cs` and `cz`. 
And unfortunately the result is no. I will fix it in next release `v0.25.3`.

https://atom.io/packages/atom-i18n

**Pull request merged**
