### PR TITLE
Created initial nl translations

### PR DESCRIPTION
**Pull request by laurensbrand**
Created initial nl translations. It is so far only for Mac and not everything yet the settings menu

### CODE REVIEW

**Comment by liuderchi** [comment]
@laurensbrand Thanks for translating Dutch for #32 :+1:

**Comment by liuderchi** [comment]
@laurensbrand  I'm sorry this PR is broken due to unknown reason.

May you create another PR again?

**Comment by laurensbrand** [comment]
Done, hope I did it right

**Comment by liuderchi** [comment]
@laurensbrand it looks like you created PR in your forked repo.

Please create new PR in this repo in order to compare your `nl` with `master` here.

**Pull request merged**
