### PR TITLE
Update ru/settings.cson

### PR DESCRIPTION
**Pull request by Dr-Yukon**
Тут ещё пилить и пилить, но по крайней мере сокращено количество детских ошибок

This PR/Translation is about #ISSUE_NUMBER.

**files translated**:
  - [ ] `def/--LOCALE-CODE--/about.cson`
  - [ ] `def/--LOCALE-CODE--/context.cson`
  - [ ] `def/--LOCALE-CODE--/menu_darwin.cson`
  - [ ] `def/--LOCALE-CODE--/menu_linux.cson`
  - [ ] `def/--LOCALE-CODE--/menu_win32.cson`
  - [x] `def/--LOCALE-CODE--/settings.cson`
  - [ ] `def/--LOCALE-CODE--/welcome.cson`

**validation**
  - [ ] I've validated my translation locally by running

`npm run validation -- --locale MY_LOCALE`

### CODE REVIEW

**Comment by liuderchi** [comment]
@Dr-Yukon Thanks for your contribution!
Would you please help merge all your changes (#244, #245, #246, #247, #248 ) into this PR?

**Comment by Dr-Yukon** [comment]
I don't know Github merging

**Comment by liuderchi** [comment]
@Dr-Yukon Just follow these steps in your terminal,
please let me know if you encountered any problems!

```
# in your local forked repo, navigate to this PR feature branch
git checkout patch-6

# merge all your PR branches
$ git merge patch-5 patch-4 patch-3 patch-2 patch-1 -m 'merge all patches'

# update changes to remote
$ git push
```

**Comment by Dr-Yukon** [comment]
i don't use git ;( only web github

**Comment by liuderchi** [comment]
I will use squash commits to merge 👋

**Pull request merged**
