### PR TITLE
[DE] Translate for settings.cson

### PR DESCRIPTION
**Pull request by queenar**
Changed some english texts and spellings.

This PR/Translation is about #47.

**files translated**:
  - [ ] `def/--LOCALE-CODE--/about.cson`
  - [ ] `def/--LOCALE-CODE--/context.cson`
  - [ ] `def/--LOCALE-CODE--/menu_darwin.cson`
  - [ ] `def/--LOCALE-CODE--/menu_linux.cson`
  - [ ] `def/--LOCALE-CODE--/menu_win32.cson`
  - [x] `def/--LOCALE-CODE--/settings.cson`
  - [ ] `def/--LOCALE-CODE--/welcome.cson`

**validation**
  - [ ] I've validated my translation locally by running

`npm run validation -- --locale MY_LOCALE`

### CODE REVIEW

**Comment by queenar** [comment]
my first try with github. hope i haven't forgotten anything. :)

**Comment by liuderchi** [comment]
@queenar please ignore the CI check failure message.
I will run validation code manually and hopefully this PR will be merged soon.

TODO reminder
  - [ ] add to contributor list
  - [ ] update CODEOWNER

**Comment by liuderchi** [comment]
@Acer54 I'd like to invite you to revie since those translation were contributed by you 👍

**Comment by liuderchi** [comment]
Thank you @queenar @Acer54 let's merge it 🎉

**Pull request merged**
