### PR TITLE
[TH] Translate for About, Context, Menus and Welcome

### PR DESCRIPTION
**Pull request by sitdh**
This PR/Translation is about #98.

**files translated**:
  - [x] `def/th/about.cson`
  - [x] `def/th/context.cson`
  - [x] `def/th/menu_darwin.cson`
  - [x] `def/th/menu_linux.cson`
  - [x] `def/th/menu_win32.cson`
  - [ ] `def/th/settings.cson`
  - [x] `def/th/welcome.cson`

**validation**
  - [x] I've validated my translation locally by running

`npm run validation -- --locale th`

### CODE REVIEW

**Comment by sitdh** [comment]
@liuderchi Could you add `th` in `spec/locales.js` please.

**Comment by liuderchi** [comment]
@sitdh don't worry about the CI failure message since Thai translation is not included in CI check script. I would manually check your translation.

Please notify me if you want this PR to be merged.

**Comment by liuderchi** [comment]
@sitdh you may add `'th',` at [locales.js](https://github.com/liuderchi/atom-i18n/blob/master/spec/locales.js#L14) then run `npm run validation -- --locale th`

TODO for myself
  - [ ] update contributor to README.md
  - [ ] add entry to README.md
  - [ ] better experience for new locale translation: omit locales.js when validate single locale

**Comment by liuderchi** [comment]
Let's merge it 👍

**Comment by sitdh** [comment]
@liuderchi Sorry, I'm working on my thesis. I'm still translating 2 files remain :)

**Comment by liuderchi** [comment]
@sitdh never mind 💯

**Pull request merged**
