### PR TITLE
Corrected some typos in the French translation

### PR DESCRIPTION
**Pull request by Vivalzar**
I have corrected some typos in the French translation. I've also corrected several '&' in the menu.

### CODE REVIEW

**Comment by liuderchi** [comment]
@Vivalzar thanks for fixing typo. :100: 

@Vivalzar and @chezyann:

Is it fine for you that hotkey hint format is not consistent?
( some lies inside of some word while some wrapped in braces in the end )

**Comment by Vivalzar** [comment]
Well, I prefer that the hotkey be in the actual text when possible. I find it a lot more readable and have seen that in other softwares.

Waiting for the answer from @chezyann here. If the consistency is more important, then I'll keep only the typos-fixing.

**Comment by Vivalzar** [comment]
I have a question. Why do we have to put the hotkey in parentheses at the end, as per the Translation Guide? It makes sense when the alphabets are different, but less when they are the same.

I've checked MS Office and Notepad++, and the hotkeys _are_ different for each language. They've let translators choose the best character for the hotkeys. We could do the same. It would be both usable and readable. And it doesn't impact keyboard shortcuts, which are an entirely different thing.

**Comment by liuderchi** [comment]
@Vivalzar thanks for your survey.

> We could do the same. It would be both usable and readable. And it doesn't impact keyboard shortcuts, which are an entirely different thing.

Yes it's correct. I thought hotkey hint need to be consistent among each languages.
I will *remove it from the Translation Guide*.

**Comment by Vivalzar** [comment]
Added 2 commits with the proper hotkeys.

**Pull request merged**
