### PR TITLE
Chinese(Trad.) Translation: context-menu, menus, settings

### PR DESCRIPTION
**Pull request by liuderchi**
related issue #11 

- [x] context menu
- menus for 3 platforms
  - [x] darwin
  - [x] win32
  - [x] linux
- [x] settings

NOTE: this branch will keep updating until go through each cson files

### CODE REVIEW

**Comment by Brli** [comment]
https://atom.io/packages/cht-menu
There are updates, please sync with it

**Comment by liuderchi** [comment]
@Brli Thanks for that.

I would consider it as main reference but also review its translation.
Perhaps not gonna 100% sync with it.

**Comment by Brli** [comment]
hm, you may also want to update front README.md to grant contribution for Trad. Chinese? 😝

**Comment by liuderchi** [comment]
@Brli thanks :smile:

**Pull request merged**
