### PR TITLE
translate all def/fa files for persian (fa) language.

### PR DESCRIPTION
**Pull request by abilogos**
This PR/Translation is about #209 and #291 .

**files translated**:
  - [x] `def/--LOCALE-CODE--/about.cson`
  - [x] `def/--LOCALE-CODE--/context.cson`
  - [x] `def/--LOCALE-CODE--/menu_darwin.cson`
  - [x] `def/--LOCALE-CODE--/menu_linux.cson`
  - [x] `def/--LOCALE-CODE--/menu_win32.cson`
  - [X] `def/--LOCALE-CODE--/settings.cson`
  - [x] `def/--LOCALE-CODE--/welcome.cson`

**validation**
  - [x] I've validated my translation locally by running

`npm run validation -- --locale MY_LOCALE`

### CODE REVIEW

**Comment by abilogos** [comment]
hi @liuderchi ,
after i run the test it gets me some weird error and since i am not familiar with node, i didnt understand what was i wrong.
the error log is:

```npm run validation -- --locale fa

> atom-i18n@0.24.1 validation /home/ali/workspace/atom-i18n
> mocha spec/validation.js "--locale" "fa"



  validation
    package.json validation
      ✓ checks locale options list in configSchema in package.json
    cson file validation
      checking template/settings.cson `controls.*._id` according atom config-schema.js
fetching https://raw.githubusercontent.com/atom/atom/v1.22.0-beta0/src/config-schema.js...
        1) fetches descriptive part of config-schema.js then compares keys of settings.cson with it
      checking each cson files of all locales
        checking locale fa
          checking "fa/menu_darwin.cson"
            ✓ has no error loading cson
            ✓ has consistent flatten keys with template
            ✓ has no special char in values of cson
          checking "fa/menu_linux.cson"
            ✓ has no error loading cson
            ✓ has consistent flatten keys with template
            ✓ has no special char in values of cson
            ✓ has valid hotkey hints if required
          checking "fa/menu_win32.cson"
            ✓ has no error loading cson
            ✓ has consistent flatten keys with template
            ✓ has no special char in values of cson
            ✓ has valid hotkey hints if required
          checking "fa/context.cson"
            ✓ has no error loading cson
            ✓ has consistent flatten keys with template
            ✓ has no special char in values of cson
          checking "fa/settings.cson"
            ✓ has no error loading cson
            ✓ has consistent flatten keys with template
            ✓ has no special char in values of cson
          checking "fa/about.cson"
            ✓ has no error loading cson
            ✓ has consistent flatten keys with template
            ✓ has no special char in values of cson
          checking "fa/welcome.cson"
            ✓ has no error loading cson
            ✓ has consistent flatten keys with template
            ✓ has no special char in values of cson


  24 passing (2s)
  1 failing

  1) validation
       cson file validation
         checking template/settings.cson `controls.*._id` according atom config-schema.js
           fetches descriptive part of config-schema.js then compares keys of settings.cson with it:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/ali/workspace/atom-i18n/spec/validation.js)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)
  



npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! atom-i18n@0.24.1 validation: `mocha spec/validation.js "--locale" "fa"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the atom-i18n@0.24.1 validation script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ali/.npm/_logs/2020-12-30T13_45_58_342Z-debug.log```

its something about timeout !
can you help me with this?

**Comment by liuderchi** [comment]
@abilogos The script including some grammar/syntax check, but now I ran this PR locally without any error. 👍

**Review by liuderchi — APPROVED** [review]
@abilogos Thanks for your contribution! 💯

**Comment by abilogos** [comment]
Thanks @liuderchi.

**Comment by liuderchi** [comment]
@abilogos Persian translation has been released in v0.25.0
https://atom.io/packages/atom-i18n

**Pull request merged**
