### PR TITLE
Update spanish translation for new keys and values

### PR DESCRIPTION
**Pull request by stsewd**
Translated into Spanish new keys and values added on 6d500fc6a09c2fb0dc0600b4f5a25f2d0fbd978a.

Also I fixed a typo on `about.cson `.

### CODE REVIEW

**Comment by liuderchi** [comment]
@stsewd thanks for translation :100: 
to tidy up branches it's nice to rebase your branch to latest `master` and make a force push : ]

you may do
`git checkout master && git pull`

then you may tidy up your PR branch
`git checkout update_spanish_translation && git rebase master && git push -f`

in this case there won't be conflicts since I am not editing `def/es/*`

**Comment by stsewd** [comment]
@liuderchi I just made the rebase, I had no idea how rebase worked, thanks for the explanation!

**Comment by liuderchi** [comment]
@stsewd that's really a git magic :tada: 
it's ready to merge.

BTW It looks like you got permission to create branch on this repo.
is that some kind of magic of collaborator?

**Comment by liuderchi** [comment]
Well I found that it's a GitHub's design to let collaborators have `push access to this repo`

**Comment by stsewd** [comment]
@liuderchi I think so, but if It's not ok for you, I could keeping creating branches on my fork.

**Comment by liuderchi** [comment]
IMO it's better to isolate our own development to avoid accidentally changing others branches.

originally I just want to tryout assignee so I use collaborators : ]

**Pull request merged**
