### PR TITLE
Add Korean translation (100%)

### PR DESCRIPTION
**Pull request by preco21**
Thank you for the awesome project! 👍 

I just got some translations for Korean language.

~~Currently, the remaining menu strings are in progress translation. Other strings are completely translated.~~

Feel free to merge this PR ~~, or you can wait for the full translation.~~

All strings has been completely translated! 🎉 

Also, if you want to verify translations, I can call my friends to review all translations.

### CODE REVIEW

**Comment by liuderchi** [comment]
@preco21 Thank you so much for making this project better :tada: 

> Feel free to merge this PR, or you can wait for the full translation.

That's nice and I will notify you before I merge it.

> if you want to verify translations, I can call my friends to review all translations.

Really excited. Are your friends using Atom too?
I'm considering which one is better :
  - let your friends try it out earlier on Atom (merging this PR before 100%),
  - or let them review plain text file here?

**Comment by preco21** [comment]
@liuderchi I just gave forked repo's address to my friends to test out translation. After that, I'll assign friends here to review plain text.

**Comment by preco21** [comment]
@chibichichi @Riyeon

**Comment by chibichichi** [comment]
at 93 lines, I think "메뉴 바" is better than "메뉴 막대"

**Comment by chibichichi** [comment]
at setting docs, 99 lines, you should change "윈도우" to "창" or changed 98 lines.

**Comment by preco21** [comment]
@liuderchi LGTM 💯

**Comment by liuderchi** [comment]
LGTM (too bad I can't read it). 
Thanks so much for fantastic i18n for :kr: 

@preco21 Would like to wait for your friend @Riyeon 's review?

**Comment by preco21** [comment]
@liuderchi @Riyeon had already feedback me directly in private chat. He also said LGTM (Looks good to me).

**Comment by liuderchi** [comment]
Good News: Korean translation has been published in `v0.2.0` :tada: 

Please keep updating Atom and watching for new UI changes.
If found new Item require translation, please send issues.

Thanks again for contribution from 0 to :100:

**Pull request merged**
