### PR TITLE
Updated german translation for #100.

### PR DESCRIPTION
**Pull request by polynoman**
This PR/Translation is about #100  .

**files translated**:
  - [x] `def/--LOCALE-CODE--/about.cson`
  - [ ] `def/--LOCALE-CODE--/context.cson`
  - [x] `def/--LOCALE-CODE--/menu_darwin.cson`
  - [x] `def/--LOCALE-CODE--/menu_linux.cson`
  - [x] `def/--LOCALE-CODE--/menu_win32.cson`
  - [ ] `def/--LOCALE-CODE--/settings.cson`
  - [x] `def/--LOCALE-CODE--/welcome.cson`

**validation**
  - [x] I've validated my translation locally by running

`npm run validation -- --locale de`

### CODE REVIEW

**Comment by liuderchi** [comment]
@Acer54 @queenar @socialmedialabs @silas229 @Tz3r0
Would you like to review this German translation?

**Comment by socialmedialabs** [comment]
@liuderchi no, I'm sorry, I have moved away from Atom to VS Code in the meantime.

**Comment by polynoman** [comment]
I have no idea how that file got changed.

**Comment by liuderchi** [comment]
Thank you @polynoman 💯 let's merge it

**Pull request merged**
